### ISSUE TITLE
Add support for bi-directional websockets in VSCode

### ISSUE THREAD

**Issue by fedario** [holoviz/holoviews#3624]
## Description

When plotting interactively using Datashader and Holoviews it does not update the data shading when zooming in.
This is only the case when plotting via a Jupyter session in VSCode. It works when using a standalone Jupyter session.

Here is the code I have used:

```Python
# %%
import os
import datashader as ds
import pandas as pd
from colorcet import fire
from datashader import transfer_functions as tf
import holoviews as hv
import geoviews as gv
from holoviews.operation.datashader import datashade
hv.extension("bokeh")

data_path = os.path.expanduser("~/Downloads/test_data/nyc_taxi.csv")

df = pd.read_csv(
    data_path,
    usecols=["dropoff_x",  "dropoff_y"],
)

agg = ds.Canvas().points(df, "dropoff_x", "dropoff_y")
tf.set_background(tf.shade(agg, cmap=fire), "black")

url = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{Z}/{Y}/{X}.jpg"
tile_opts = dict(
    width=1000,
    height=600,
    xaxis=None,
    yaxis=None,
    bgcolor="black",
    show_grid=False,
)
map_tiles = gv.WMTS(url).opts(style=dict(alpha=0.5), plot=tile_opts)
points = hv.Points(df, ["dropoff_x", "dropoff_y"])
taxi_trips = datashade(
    points,
    x_sampling=1,
    y_sampling=1,
    cmap=fire,
    width=1000,
    height=600,
)

map_tiles * taxi_trips
```

## Environment (truncated)

OS: Ubuntu 18.04

VSCode version: 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8 x64)

```
# Name                    Version                   Build  Channel
anaconda                  2019.03                  py37_0  
bokeh                     1.0.4                    py37_0  
colorcet                  2.0.1                      py_0    pyviz
conda                     4.6.11                   py37_0  
conda-build               3.17.8                   py37_0  
conda-env                 2.6.0                         1  
conda-verify              3.1.1                    py37_0  
datashader                0.6.8                      py_0    pyviz
geos                      3.7.1                he6710b0_0  
geoviews                  1.6.2                      py_0    pyviz
geoviews-core             1.6.2                      py_0  
holoviews                 1.11.0             pyh39e3cac_0    pyviz    <--- same result with 1.12.1
hvplot                    0.4.0                      py_0    pyviz
ipykernel                 5.1.0            py37h39e3cac_0  
ipython                   7.4.0            py37h39e3cac_0  
ipython_genutils          0.2.0                    py37_0  
ipywidgets                7.4.2                    py37_0  
jupyter                   1.0.0                    py37_7  
jupyter_client            5.2.4                    py37_0  
jupyter_console           6.0.0                    py37_0  
jupyter_core              4.4.0                    py37_0  
jupyterlab                0.35.4           py37hf63ae98_0  
jupyterlab_server         0.2.0                    py37_0  
python                    3.7.3                h0371630_0  
```

Previously opened [here](https://github.com/pyviz/datashader/issues/739).

**Comment by philippjfr** [comment]
As I mentioned in the corresponding datashader issue, interactive datashader plots require a live websocket. I'm not aware of a mechanism or API to open a websocket in the VSCode  jupyter integration. I'd love to be proven wrong on that front though, do you know if ipywidgets work inside VSCode?

**Comment by fedario** [comment]
If I understand [this issue](https://github.com/Microsoft/vscode-python/issues/3429) correctly, not yet.

**Comment by KestutisMa** [comment]
> If I understand [this issue](https://github.com/Microsoft/vscode-python/issues/3429) correctly, not yet.

According to latest replies, at least one user reported that it works now?

**Comment by jmakov** [comment]
Doesn't work.

**Comment by Hoxbro** [comment]
Unless I'm misunderstanding this should now be supported when having `jupyter_bokeh` (v3.0.7) installed.

**Comment by jmakov** [comment]
Downgraded Jupyterlab and installed jupyter_bokeh 3.0.7, same issue.

**Comment by Hoxbro** [comment]
Can you post a MRE?

**Comment by jmakov** [comment]
```
import polars

polars.DataFrame({"col1": range(10)}).plot(datashade=True)
```

![Peek 2024-01-23 21-58](https://github.com/holoviz/holoviews/assets/2602122/03cdcbdc-be9c-4337-8e38-15c7e287b1c4)

**Comment by jmakov** [comment]
Thank you very much for the feedback. Do you have any idea why it's not working on my side? Can you perhaps share versions of VSCode, `jupyter_bokeh`, `jupyterlab` or other relevant packages? On the VSCode side, it already forwards all the ports so guess that's not the issue.

**Comment by Hoxbro** [comment]
I think the problem is the detection of comms, can you try running:

``` python
import panel as on
print(pn.config.comms)
```

This should be printing vscode. 

My output of `hv.show_version` is:
``` yaml
Python              :  3.11.7 | packaged by conda-forge | (main, Dec 23 2023, 14:43:09) [GCC 12.3.0]
Operating system    :  Linux-6.6.6-76060606-generic-x86_64-with-glibc2.35
Panel comms         :  default

holoviews           :  1.18.2a2.post33+g45254b49f

bokeh               :  3.3.3
colorcet            :  3.0.1.post15+g34b3992
cudf                :  -
dask                :  2024.1.0
datashader          :  0.16.1a1.post1+g90ad4cb
geoviews            :  1.11.1a0+g7836dda.dirty
hvplot              :  0.9.1rc1.post1+gad29d30
ibis                :  -
IPython             :  8.20.0
jupyter_bokeh       :  3.0.7
jupyterlab          :  3.6.7
matplotlib          :  3.8.2
networkx            :  3.2.1
notebook            :  6.5.6
numba               :  0.59.0rc1
numpy               :  1.26.3
pandas              :  2.1.4
panel               :  1.4.0a1.post17+g2a892a3a2
param               :  2.0.3.dev0+g594c02e.d20240122
PIL                 :  -
plotly              :  5.18.0
pyarrow             :  14.0.2
pyviz_comms         :  2.3.2
scipy               :  1.12.0
skimage             :  -
spatialpandas       :  0.4.10
streamz             :  0.6.4
xarray              :  2024.1.0
```
