### ISSUE TITLE
Slightly corrupted images when using `datashade` with bokeh backend (but not with plotly)

### ISSUE THREAD

**Issue by hrbigelow** [holoviz/holoviews#5866]
(Issue also illustrated on [discourse](https://discourse.holoviz.org/t/slightly-corrupted-images-when-using-datashade-with-bokeh-backend-but-not-with-plotly/5931))

Using:

bokeh 3.2.2
plotly 5.16.1
datashader 0.15.2
holoviews 1.17.1

With the following setup:

```python
import numpy as np
import pandas as pd
import holoviews as hv
from holoviews.operation.datashader import datashade

N = 10
x = np.linspace(0, 1000, N)
y = np.sin(x / 30)
df = pd.DataFrame(dict(x=x,y=y))
```

When I do:

```python
hv.extension('bokeh')
opts = hv.opts.RGB(width=900, height=400)
img = datashade(hv.Path(df, kdims=['x','y']), width=900, height=400)
img.opts(opts)
img
```

I see a line with artifacts.  This is some sort of bug (see below).  I've stepped through a lot of the code in [holoviews/plotting/bokeh/element](https://github.com/holoviz/holoviews/blob/e2f06d08c3a255b83dabca42dc6636e888360225/holoviews/plotting/bokeh/element.py#L1586) and other files, for example.  Unfortunately it seems too complex for me to debug.  But, I'm thinking there is some bug in the downstream processing, since the output images that come directly from datashader look perfect (see below)

![image](https://github.com/holoviz/holoviews/assets/5355286/db30c63f-19dc-491c-9519-0add21bc9483)

Any help would be much appreciated.  As it is, this is unfortunately not usable quality, it is too visually distracting.

When I instead use the plotly backend but everything else the same:

```python
hv.extension('plotly')
opts = hv.opts.RGB(width=900, height=400)
img = datashade(hv.Path(df, kdims=['x','y']), width=900, height=400)
img.opts(opts)
img
```

The line has no artifacts:

![image](https://github.com/holoviz/holoviews/assets/5355286/d7b1e003-4575-4d01-a4b7-9be769305888)

Finally, I can confirm that this is not an issue with datashader image generation itself.  When I do:

```python
cvs = ds.Canvas(x_range=[0, 1000], y_range=[-1,1], 
         plot_height=400, plot_width=900)
agg = cvs.line(df, 'x', 'y', agg=ds.any())
tf.shade(agg)
```

I see a perfectly rendered line plot:

![image](https://github.com/holoviz/holoviews/assets/5355286/87038488-3723-4db9-8f66-b8b34f871f6c)

Thanks in advance!

**Comment by Hoxbro** [comment]
Running the code on my computer does not seem to give the corrupted image: 
![image](https://github.com/holoviz/holoviews/assets/19758978/cf64e3ab-275a-452d-9cf9-81e1d15d3aa8)

Can I get you to paste the output of `hv.show_versions()`

**Comment by hrbigelow** [comment]
Thank you Hoxbro.  Sure, I see:

```bash
Python              :  3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:17) [GCC 12.2.0]
Operating system    :  Linux-5.15.0-78-generic-x86_64-with-glibc2.35
Panel comms         :  default

holoviews           :  1.17.1

bokeh               :  3.2.2
colorcet            :  3.0.1
cudf                :  -
dask                :  2023.8.1
datashader          :  0.15.2
geoviews            :  -
hvplot              :  0.8.4
ibis                :  -
IPython             :  8.14.0
jupyter_bokeh       :  -
jupyterlab          :  4.0.5
matplotlib          :  3.7.2
networkx            :  3.1
notebook            :  7.0.2
numba               :  0.57.1
numpy               :  1.24.4
pandas              :  2.0.3
panel               :  1.2.1
param               :  1.13.0
PIL                 :  10.0.0
plotly              :  5.16.1
pyarrow             :  12.0.1
scipy               :  1.11.2
skimage             :  0.21.0
spatialpandas       :  -
streamz             :  0.6.4
xarray              :  2023.8.0
```

**Comment by Hoxbro** [comment]
I can't see any obvious reasons why it does not work. Can you paste the output of `conda list` ?



For what it is worth, I created a new environment and got.
``` yaml
Python              :  3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:34:09) [GCC 12.3.0]
Operating system    :  Linux-6.4.6-76060406-generic-x86_64-with-glibc2.35
Panel comms         :  default

holoviews           :  1.17.1

bokeh               :  3.2.2
colorcet            :  3.0.1
cudf                :  -
dask                :  2023.8.1
datashader          :  0.15.2
geoviews            :  -
hvplot              :  -
ibis                :  -
IPython             :  8.14.0
jupyter_bokeh       :  -
jupyterlab          :  4.0.5
matplotlib          :  3.7.2
networkx            :  -
notebook            :  7.0.2
numba               :  0.57.1
numpy               :  1.24.4
pandas              :  2.0.3
panel               :  1.2.1
param               :  1.13.0
PIL                 :  10.0.0
plotly              :  -
pyarrow             :  13.0.0
scipy               :  1.11.2
skimage             :  -
spatialpandas       :  -
streamz             :  -
xarray              :  2023.8.0
```
