### ISSUE TITLE
Linked Selection is broken for Bar charts

### ISSUE THREAD

**Issue by ahuang11** [holoviz/holoviews#6248]
Link selections with bar charts seem broken:
```python
import numpy as np
import pandas as pd
import holoviews as hv

from holoviews.util.transform import dim
from holoviews.selection import link_selections
from holoviews.operation import gridmatrix
from holoviews.operation.element import histogram
from holoviews import opts
from bokeh.sampledata.autompg import autompg
autompg

hv.extension('bokeh', 'plotly', width=100)

autompg_ds = hv.Dataset(autompg, ['yr', 'name', 'origin'])

mopts = opts.Points(size=2, tools=['box_select','lasso_select'], active_tools=['box_select'])
w_accel_scatter = hv.Scatter(autompg_ds, 'weight', 'accel')
mpg_hist = histogram(autompg_ds, dimension='mpg', normed=False).opts(color="green")
violin = hv.Violin(autompg_ds, [], 'hp')

mpg_ls = link_selections.instance()
mpg_ls(w_accel_scatter + mpg_hist + violin)
```

https://github.com/holoviz/holoviz/assets/15331990/3aaa03a3-3910-4867-9d47-2465ece13253

**Comment by hoxbro** [comment]
Versions? Does it work outside vscode?

Is it related to the chart PR?

**Comment by philippjfr** [comment]
Can't reproduce this one.

**Comment by ahuang11** [comment]
Actually only lasso select doesn't work.

**Comment by hoxbro** [comment]
> latest version of HoloViews

What is the latest? Main or the latest release.

**Comment by philippjfr** [comment]
Main

**Comment by hoxbro** [comment]
Seems to work if you update `hv.Scatter` to `hv.Points`: `hv.Points(autompg_ds, kdims=['weight', 'accel'])`. Though it does not work if I change the `opts` to Scatter.
![image](https://github.com/holoviz/holoviews/assets/19758978/fb87c1fa-29ac-4e00-8825-a3d22be5e3e8)


<details>
  <summary><code>hv.show_versions</code> </summary>

``` yaml
Python              :  3.12.3 | packaged by conda-forge | (main, Apr 15 2024, 18:38:13) [GCC 12.3.0]
Operating system    :  Linux-6.8.0-76060800daily20240311-generic-x86_64-with-glibc2.35
Panel comms         :  default

holoviews           :  1.19.0a4.dev6+ge2a23d1c6

bokeh               :  3.4.1
colorcet            :  3.1.0
cudf                :  -
dask                :  2024.5.1
datashader          :  0.16.2rc1
geoviews            :  1.12.0.post3+geed196d
hvplot              :  0.10.1.dev2+g23d9f0c.d20240530
ibis-framework      :  9.0.0
IPython             :  8.24.0
jupyter_bokeh       :  4.0.4
jupyterlab          :  4.2.1
matplotlib          :  3.8.4
networkx            :  3.3
notebook            :  7.2.0
numba               :  0.59.1
numpy               :  1.26.4
pandas              :  2.2.2
panel               :  1.5.0a3.post1.dev19+g59c2be2e.d20240603
param               :  2.1.1a1.dev3+g7c9d7c6.d20240530
pillow              :  10.3.0
plotly              :  5.22.0
pyarrow             :  16.1.0
pyviz_comms         :  3.0.2
scikit-image        :  0.22.0
scipy               :  1.13.1
spatialpandas       :  0.4.10
streamz             :  0.6.4
tsdownsample        :  0.1.3
xarray              :  2024.5.0
```

</details>
