### ISSUE TITLE
Bars in Overlays with timezone-aware datetimes shows a big black box

### ISSUE THREAD

**Issue by nfi-hashicorp** [holoviz/holoviews#6364]
#### ALL software version info

Using VS Code ipython notebook, bokeh backend, macOS 14.5

```toml
[tool.poetry]
name = "blah"
version = "0.1.0"
description = ""
authors = ["Nick Irvine <115657443+nfi-hashicorp@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^2.1.0"
pandas = "^2.2.2"
holoviews = "^1.19.1"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

```shell
% code --version
1.92.1
eaa41d57266683296de7d118f574d0c2652e1fc4
arm64
```

#### Description of expected behavior and the observed behavior

When combining data with tz-aware datetimes, bars and overlays, we get this garbled mess:

<img width="338" alt="image" src="https://github.com/user-attachments/assets/521394c4-a6b3-4b09-ab87-295c57f1346d">

instead of this:

<img width="315" alt="image" src="https://github.com/user-attachments/assets/5174d7a4-daac-4256-a5cf-44ad71f77c96">

#### Complete, minimal, self-contained example code that reproduces the issue

Based on bars example

```python 
import holoviews as hv
import pandas as pd
hv.extension('bokeh')
from bokeh.plotting import show

data = pd.DataFrame({"x": pd.date_range("2017-01-01", "2017-01-03"), "y": [0, 2, -1]})
data_utc = pd.DataFrame({"x": pd.date_range("2017-01-01", "2017-01-03", tz="UTC"), "y": [0, 2, -1]})

bars = hv.Bars(data, ["x"], ["y"])
bars_utc = hv.Bars(data_utc, ["x"], ["y"])
# works
show(hv.render(bars))
# works
show(hv.render(hv.Overlay([bars])))
# works
show(hv.render(bars_utc))
# busted
show(hv.render(hv.Overlay([bars_utc])))
```

Renders as:

<img width="324" alt="image" src="https://github.com/user-attachments/assets/e2b46a8e-ecf9-40f8-9022-b5f3dd38fcdc">

# Workaround

Strip the timezone

```python
data_stripped = data_utc.copy()
data_stripped["x"] = data_utc["x"].apply(lambda x: x.tz_convert(None))
bars_stripped = hv.Bars(data_stripped, ["x"], ["y"])
show(hv.render(hv.Overlay([bars_stripped])))
```

<img width="317" alt="image" src="https://github.com/user-attachments/assets/46b8a993-2baf-4666-806f-8a2f5b7d321a">

- [x] I may be interested in making a pull request to address this
