### ISSUE TITLE
Setting bounds on `Image` and `ImageStack` does not always work

### ISSUE THREAD

**Issue by hoxbro** [holoviz/holoviews#6622]
#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc should be added within the dropdown below.)

<details>
    <summary>Software Version Info</summary>

```yaml
Python              :  3.13.3 | packaged by conda-forge | (main, Apr 14 2025, 20:44:03) [GCC 13.3.0]
Operating system    :  Linux-6.15.2-arch1-1-x86_64-with-glibc2.41
Panel comms         :  default

holoviews           :  1.21.0b3.post1.dev3+g01b8f0205

bokeh               :  3.7.3
colorcet            :  3.1.0
cudf                :  -
cupy                :  13.4.1
dask                :  2025.5.1
dask-expr           :  -
datashader          :  0.18.1.post1.dev1+g7def0b7
geoviews            :  1.14.0.post1.dev10+g5092afe
hvplot              :  0.11.3.post1.dev15+gd806f64.d20250611
ibis-framework      :  10.5.0
IPython             :  9.3.0
ipywidgets-bokeh    :  1.6.0
jupyter-bokeh       :  4.0.5
jupyterlab          :  4.4.3
matplotlib          :  3.10.3
networkx            :  3.5
notebook            :  -
numba               :  0.61.2
numpy               :  2.2.6
pandas              :  2.3.0
panel               :  1.7.1.post1.dev41+gd6b25046b.d20250611
param               :  2.2.0a2.post1.dev9+ga2bd29b.d20250611
pillow              :  11.2.1
plotly              :  6.1.2
pyarrow             :  20.0.0
pyviz-comms         :  3.0.4
scikit-image        :  0.25.2
scipy               :  1.15.2
spatialpandas       :  0.5.0.post1.dev5+g5e10dbd
streamz             :  -
tsdownsample        :  0.1.4.1
xarray              :  2025.4.0
```
</details>

#### Description of expected behavior and the observed behavior

First reported by @maximlt [here](https://github.com/holoviz/holoviews/pull/6619#discussion_r2145128530).

I would expect all the examples to work.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import numpy as np
import xarray as xr

import holoviews as hv

hv.extension("bokeh")
x, y = np.arange(4), np.arange(4) + 100
cat = ["A"]
a = np.diag(np.ones(4))[:, :, np.newaxis]
da = xr.DataArray(a, dims=("y", "x", "cat"), coords={"y": y, "x": x, "cat": cat})

hv.ImageStack(da, kdims=["x", "y"], vdims=["cat"])  # Works
# hv.ImageStack(a, bounds=(1, 1, 4, 4)) # Fails
# hv.ImageStack(da, bounds=(1, 101, 4, 104)) # Fails

da = xr.DataArray(a[:, :, 0], dims=("y", "x"), coords={"y": y, "x": x})
hv.Image(da)  # Works
hv.Image(a, bounds=(1, 1, 4, 4)) # Works
# hv.Image(da, bounds=(1, 1, 4, 4)) # Fails

```

#### Screenshots or screencasts of the bug in action

- [ ] I may be interested in making a pull request to address this
